# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 491)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 20, 461, 401))
        self.widget.setStyleSheet("background-color: rgb(32, 91, 255);")
        self.widget.setObjectName("widget")
        self.pB5 = QtWidgets.QPushButton(self.widget)
        self.pB5.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.pB5.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB5.setObjectName("pB5")
        self.pB12 = QtWidgets.QPushButton(self.widget)
        self.pB12.setGeometry(QtCore.QRect(80, 20, 50, 50))
        self.pB12.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB12.setObjectName("pB12")
        self.pB19 = QtWidgets.QPushButton(self.widget)
        self.pB19.setGeometry(QtCore.QRect(140, 20, 50, 50))
        self.pB19.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB19.setObjectName("pB19")
        self.pB26 = QtWidgets.QPushButton(self.widget)
        self.pB26.setGeometry(QtCore.QRect(200, 20, 50, 50))
        self.pB26.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB26.setObjectName("pB26")
        self.pB33 = QtWidgets.QPushButton(self.widget)
        self.pB33.setGeometry(QtCore.QRect(260, 20, 50, 50))
        self.pB33.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB33.setObjectName("pB33")
        self.pB40 = QtWidgets.QPushButton(self.widget)
        self.pB40.setGeometry(QtCore.QRect(320, 20, 50, 50))
        self.pB40.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB40.setObjectName("pB40")
        self.pB47 = QtWidgets.QPushButton(self.widget)
        self.pB47.setGeometry(QtCore.QRect(380, 20, 50, 50))
        self.pB47.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB47.setObjectName("pB47")
        self.pB4 = QtWidgets.QPushButton(self.widget)
        self.pB4.setGeometry(QtCore.QRect(20, 80, 50, 50))
        self.pB4.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB4.setObjectName("pB4")
        self.pB18 = QtWidgets.QPushButton(self.widget)
        self.pB18.setGeometry(QtCore.QRect(140, 80, 50, 50))
        self.pB18.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB18.setObjectName("pB18")
        self.pB11 = QtWidgets.QPushButton(self.widget)
        self.pB11.setGeometry(QtCore.QRect(80, 80, 50, 50))
        self.pB11.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB11.setObjectName("pB11")
        self.pB25 = QtWidgets.QPushButton(self.widget)
        self.pB25.setGeometry(QtCore.QRect(200, 80, 50, 50))
        self.pB25.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB25.setObjectName("pB25")
        self.pB32 = QtWidgets.QPushButton(self.widget)
        self.pB32.setGeometry(QtCore.QRect(260, 80, 50, 50))
        self.pB32.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB32.setObjectName("pB32")
        self.pB39 = QtWidgets.QPushButton(self.widget)
        self.pB39.setGeometry(QtCore.QRect(320, 80, 50, 50))
        self.pB39.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB39.setObjectName("pB39")
        self.pB46 = QtWidgets.QPushButton(self.widget)
        self.pB46.setGeometry(QtCore.QRect(380, 80, 50, 50))
        self.pB46.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB46.setObjectName("pB46")
        self.pB3 = QtWidgets.QPushButton(self.widget)
        self.pB3.setGeometry(QtCore.QRect(20, 140, 50, 50))
        self.pB3.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB3.setObjectName("pB3")
        self.pB17 = QtWidgets.QPushButton(self.widget)
        self.pB17.setGeometry(QtCore.QRect(140, 140, 50, 50))
        self.pB17.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB17.setObjectName("pB17")
        self.pB10 = QtWidgets.QPushButton(self.widget)
        self.pB10.setGeometry(QtCore.QRect(80, 140, 50, 50))
        self.pB10.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB10.setObjectName("pB10")
        self.pB24 = QtWidgets.QPushButton(self.widget)
        self.pB24.setGeometry(QtCore.QRect(200, 140, 50, 50))
        self.pB24.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB24.setObjectName("pB24")
        self.pB31 = QtWidgets.QPushButton(self.widget)
        self.pB31.setGeometry(QtCore.QRect(260, 140, 50, 50))
        self.pB31.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB31.setObjectName("pB31")
        self.pB38 = QtWidgets.QPushButton(self.widget)
        self.pB38.setGeometry(QtCore.QRect(320, 140, 50, 50))
        self.pB38.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB38.setObjectName("pB38")
        self.pB45 = QtWidgets.QPushButton(self.widget)
        self.pB45.setGeometry(QtCore.QRect(380, 140, 50, 50))
        self.pB45.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB45.setObjectName("pB45")
        self.pB2 = QtWidgets.QPushButton(self.widget)
        self.pB2.setGeometry(QtCore.QRect(20, 200, 50, 50))
        self.pB2.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB2.setObjectName("pB2")
        self.pB16 = QtWidgets.QPushButton(self.widget)
        self.pB16.setGeometry(QtCore.QRect(140, 200, 50, 50))
        self.pB16.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB16.setObjectName("pB16")
        self.pB9 = QtWidgets.QPushButton(self.widget)
        self.pB9.setGeometry(QtCore.QRect(80, 200, 50, 50))
        self.pB9.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB9.setObjectName("pB9")
        self.pB23 = QtWidgets.QPushButton(self.widget)
        self.pB23.setGeometry(QtCore.QRect(200, 200, 50, 50))
        self.pB23.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB23.setObjectName("pB23")
        self.pB30 = QtWidgets.QPushButton(self.widget)
        self.pB30.setGeometry(QtCore.QRect(260, 200, 50, 50))
        self.pB30.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB30.setObjectName("pB30")
        self.pB37 = QtWidgets.QPushButton(self.widget)
        self.pB37.setGeometry(QtCore.QRect(320, 200, 50, 50))
        self.pB37.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB37.setObjectName("pB37")
        self.pB44 = QtWidgets.QPushButton(self.widget)
        self.pB44.setGeometry(QtCore.QRect(380, 200, 50, 50))
        self.pB44.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB44.setObjectName("pB44")
        self.pB1 = QtWidgets.QPushButton(self.widget)
        self.pB1.setGeometry(QtCore.QRect(20, 260, 50, 50))
        self.pB1.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB1.setObjectName("pB1")
        self.pB15 = QtWidgets.QPushButton(self.widget)
        self.pB15.setGeometry(QtCore.QRect(140, 260, 50, 50))
        self.pB15.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB15.setObjectName("pB15")
        self.pB8 = QtWidgets.QPushButton(self.widget)
        self.pB8.setGeometry(QtCore.QRect(80, 260, 50, 50))
        self.pB8.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB8.setObjectName("pB8")
        self.pB22 = QtWidgets.QPushButton(self.widget)
        self.pB22.setGeometry(QtCore.QRect(200, 260, 50, 50))
        self.pB22.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB22.setObjectName("pB22")
        self.pB29 = QtWidgets.QPushButton(self.widget)
        self.pB29.setGeometry(QtCore.QRect(260, 260, 50, 50))
        self.pB29.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB29.setObjectName("pB29")
        self.pB36 = QtWidgets.QPushButton(self.widget)
        self.pB36.setGeometry(QtCore.QRect(320, 260, 50, 50))
        self.pB36.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB36.setObjectName("pB36")
        self.pB43 = QtWidgets.QPushButton(self.widget)
        self.pB43.setGeometry(QtCore.QRect(380, 260, 50, 50))
        self.pB43.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB43.setObjectName("pB43")
        self.pB0 = QtWidgets.QPushButton(self.widget)
        self.pB0.setGeometry(QtCore.QRect(20, 330, 50, 50))
        self.pB0.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB0.setObjectName("pB0")
        self.pB14 = QtWidgets.QPushButton(self.widget)
        self.pB14.setGeometry(QtCore.QRect(140, 330, 50, 50))
        self.pB14.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB14.setObjectName("pB14")
        self.pB7 = QtWidgets.QPushButton(self.widget)
        self.pB7.setGeometry(QtCore.QRect(80, 330, 50, 50))
        self.pB7.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB7.setObjectName("pB7")
        self.pB21 = QtWidgets.QPushButton(self.widget)
        self.pB21.setGeometry(QtCore.QRect(200, 330, 50, 50))
        self.pB21.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB21.setObjectName("pB21")
        self.pB28 = QtWidgets.QPushButton(self.widget)
        self.pB28.setGeometry(QtCore.QRect(260, 330, 50, 50))
        self.pB28.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB28.setObjectName("pB28")
        self.pB35 = QtWidgets.QPushButton(self.widget)
        self.pB35.setGeometry(QtCore.QRect(320, 330, 50, 50))
        self.pB35.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB35.setObjectName("pB35")
        self.pB42 = QtWidgets.QPushButton(self.widget)
        self.pB42.setGeometry(QtCore.QRect(380, 330, 50, 50))
        self.pB42.setStyleSheet("border-radius : 25; \n"
"border : 2px solid black;\n"
"border-color: rgb(108, 108, 108);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.pB42.setObjectName("pB42")
        self.minimax = QtWidgets.QPushButton(self.centralwidget)
        self.minimax.setGeometry(QtCore.QRect(360, 430, 121, 23))
        self.minimax.setStyleSheet("background-color: rgb(32, 91, 255);")
        self.minimax.setObjectName("minimax")
        self.pruning = QtWidgets.QPushButton(self.centralwidget)
        self.pruning.setGeometry(QtCore.QRect(24, 430, 151, 23))
        self.pruning.setStyleSheet("background-color: rgb(32, 91, 255);")
        self.pruning.setObjectName("pruning")
        self.graphcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.graphcheck.setGeometry(QtCore.QRect(220, 430, 70, 17))
        self.graphcheck.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphcheck.setObjectName("graphcheck")
        self.Score = QtWidgets.QLabel(self.centralwidget)
        self.Score.setGeometry(QtCore.QRect(170, 0, 161, 20))
        self.Score.setObjectName("Score")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB5.setText(_translate("MainWindow", "PushButton"))
        self.pB12.setText(_translate("MainWindow", "PushButton"))
        self.pB19.setText(_translate("MainWindow", "PushButton"))
        self.pB26.setText(_translate("MainWindow", "PushButton"))
        self.pB33.setText(_translate("MainWindow", "PushButton"))
        self.pB40.setText(_translate("MainWindow", "PushButton"))
        self.pB47.setText(_translate("MainWindow", "PushButton"))
        self.pB4.setText(_translate("MainWindow", "PushButton"))
        self.pB18.setText(_translate("MainWindow", "PushButton"))
        self.pB11.setText(_translate("MainWindow", "PushButton"))
        self.pB25.setText(_translate("MainWindow", "PushButton"))
        self.pB32.setText(_translate("MainWindow", "PushButton"))
        self.pB39.setText(_translate("MainWindow", "PushButton"))
        self.pB46.setText(_translate("MainWindow", "PushButton"))
        self.pB3.setText(_translate("MainWindow", "PushButton"))
        self.pB17.setText(_translate("MainWindow", "PushButton"))
        self.pB10.setText(_translate("MainWindow", "PushButton"))
        self.pB24.setText(_translate("MainWindow", "PushButton"))
        self.pB31.setText(_translate("MainWindow", "PushButton"))
        self.pB38.setText(_translate("MainWindow", "PushButton"))
        self.pB45.setText(_translate("MainWindow", "PushButton"))
        self.pB2.setText(_translate("MainWindow", "PushButton"))
        self.pB16.setText(_translate("MainWindow", "PushButton"))
        self.pB9.setText(_translate("MainWindow", "PushButton"))
        self.pB23.setText(_translate("MainWindow", "PushButton"))
        self.pB30.setText(_translate("MainWindow", "PushButton"))
        self.pB37.setText(_translate("MainWindow", "PushButton"))
        self.pB44.setText(_translate("MainWindow", "PushButton"))
        self.pB1.setText(_translate("MainWindow", "PushButton"))
        self.pB15.setText(_translate("MainWindow", "PushButton"))
        self.pB8.setText(_translate("MainWindow", "PushButton"))
        self.pB22.setText(_translate("MainWindow", "PushButton"))
        self.pB29.setText(_translate("MainWindow", "PushButton"))
        self.pB36.setText(_translate("MainWindow", "PushButton"))
        self.pB43.setText(_translate("MainWindow", "PushButton"))
        self.pB0.setText(_translate("MainWindow", "PushButton"))
        self.pB14.setText(_translate("MainWindow", "PushButton"))
        self.pB7.setText(_translate("MainWindow", "PushButton"))
        self.pB21.setText(_translate("MainWindow", "PushButton"))
        self.pB28.setText(_translate("MainWindow", "PushButton"))
        self.pB35.setText(_translate("MainWindow", "PushButton"))
        self.pB42.setText(_translate("MainWindow", "PushButton"))
        self.minimax.setText(_translate("MainWindow", "MINIMAX"))
        self.pruning.setText(_translate("MainWindow", "MINIMAX WITH PRUNING"))
        self.graphcheck.setText(_translate("MainWindow", "Graph"))
        self.Score.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
